// Package apiinternal provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package apiinternal

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes          = "CookieAuth.Scopes"
	ReplicateBearerAuthScopes = "ReplicateBearerAuth.Scopes"
	ReplicateHeaderAuthScopes = "ReplicateHeaderAuth.Scopes"
	UploadTokenAuthScopes     = "UploadTokenAuth.Scopes"
)

// Defines values for StorageUploadResponseAvailableVariants.
const (
	Avif     StorageUploadResponseAvailableVariants = "avif"
	Original StorageUploadResponseAvailableVariants = "original"
	Webp     StorageUploadResponseAvailableVariants = "webp"
)

// BatchItem defines model for BatchItem.
type BatchItem struct {
	Duplicate *bool   `json:"duplicate,omitempty"`
	Uuid      *string `json:"uuid,omitempty"`
	ViewUrl   *string `json:"view_url,omitempty"`
}

// BatchRequest defines model for BatchRequest.
type BatchRequest struct {
	Items []BatchItem `json:"items"`
}

// BatchResponse defines model for BatchResponse.
type BatchResponse struct {
	BatchId string `json:"batch_id"`

	// ExpiresAt Unix timestamp (seconds)
	ExpiresAt int64 `json:"expires_at"`
}

// Error defines model for Error.
type Error struct {
	// Details Additional details
	Details *string `json:"details"`

	// Error Error type code
	Error string `json:"error"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// FormatVariants defines model for FormatVariants.
type FormatVariants struct {
	Medium   *VariantSize `json:"medium,omitempty"`
	Original *VariantSize `json:"original,omitempty"`
	Small    *VariantSize `json:"small,omitempty"`
}

// StorageUploadResponse defines model for StorageUploadResponse.
type StorageUploadResponse struct {
	// AvailableVariants List of available variant-families for this image
	AvailableVariants *[]StorageUploadResponseAvailableVariants `json:"available_variants,omitempty"`

	// Duplicate Indicates the uploaded file already exists for this user
	Duplicate *bool `json:"duplicate,omitempty"`

	// ImageUuid UUID of the uploaded image
	ImageUuid *string `json:"image_uuid,omitempty"`

	// Url Direct URL to the original image file
	Url *string `json:"url,omitempty"`

	// Variants URLs of available variants grouped by family
	Variants *struct {
		Avif     *FormatVariants `json:"avif,omitempty"`
		Original *FormatVariants `json:"original,omitempty"`
		Webp     *FormatVariants `json:"webp,omitempty"`
	} `json:"variants,omitempty"`

	// ViewUrl Share page URL (HTML view)
	ViewUrl *string `json:"view_url,omitempty"`
}

// StorageUploadResponseAvailableVariants defines model for StorageUploadResponse.AvailableVariants.
type StorageUploadResponseAvailableVariants string

// UploadSessionRequest defines model for UploadSessionRequest.
type UploadSessionRequest struct {
	// FileSize File size in bytes
	FileSize int64 `json:"file_size"`
}

// UploadSessionResponse defines model for UploadSessionResponse.
type UploadSessionResponse struct {
	// ExpiresAt Unix timestamp (seconds)
	ExpiresAt int64  `json:"expires_at"`
	MaxBytes  int64  `json:"max_bytes"`
	PoolId    int64  `json:"pool_id"`
	Token     string `json:"token"`
	UploadUrl string `json:"upload_url"`
}

// VariantSize defines model for VariantSize.
type VariantSize struct {
	// Animated Whether this asset is animated (e.g., GIF/WebP)
	Animated *bool `json:"animated,omitempty"`

	// Bytes File size in bytes if known
	Bytes *int64 `json:"bytes,omitempty"`

	// Height Pixel height if known
	Height *int `json:"height,omitempty"`

	// MimeType MIME type of this asset
	MimeType *string `json:"mime_type,omitempty"`
	Url      string  `json:"url"`

	// Width Pixel width if known
	Width *int `json:"width,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = Error

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = Error

// PutReplicateMultipartBody defines parameters for PutReplicate.
type PutReplicateMultipartBody struct {
	File         openapi_types.File `json:"file"`
	FileName     *string            `json:"file_name,omitempty"`
	PoolId       int64              `json:"pool_id"`
	RelativePath *string            `json:"relative_path,omitempty"`
	Sha256       *string            `json:"sha256,omitempty"`
	Size         *int64             `json:"size,omitempty"`

	// StoredPath Preferred absolute relative path within storage (e.g. original/yyyy/mm/dd/file.ext)
	StoredPath *string `json:"stored_path,omitempty"`
}

// PostUploadMultipartBody defines parameters for PostUpload.
type PostUploadMultipartBody struct {
	File openapi_types.File `json:"file"`

	// Token Alternative to Authorization header: pass upload token as multipart field
	Token *string `json:"token,omitempty"`
}

// PostUploadParams defines parameters for PostUpload.
type PostUploadParams struct {
	// Authorization Bearer <UPLOAD_TOKEN>. Alternative: submit as multipart field 'token'
	Authorization *string `json:"Authorization,omitempty"`
}

// PutReplicateMultipartRequestBody defines body for PutReplicate for multipart/form-data ContentType.
type PutReplicateMultipartRequestBody PutReplicateMultipartBody

// PostUploadMultipartRequestBody defines body for PostUpload for multipart/form-data ContentType.
type PostUploadMultipartRequestBody PostUploadMultipartBody

// PostUploadBatchesJSONRequestBody defines body for PostUploadBatches for application/json ContentType.
type PostUploadBatchesJSONRequestBody = BatchRequest

// PostUploadSessionsJSONRequestBody defines body for PostUploadSessions for application/json ContentType.
type PostUploadSessionsJSONRequestBody = UploadSessionRequest
