// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package apiv1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes      = "ApiKeyAuth.Scopes"
	UploadTokenAuthScopes = "UploadTokenAuth.Scopes"
)

// Defines values for ImageResourceAvailableVariants.
const (
	ImageResourceAvailableVariantsAvif     ImageResourceAvailableVariants = "avif"
	ImageResourceAvailableVariantsOriginal ImageResourceAvailableVariants = "original"
	ImageResourceAvailableVariantsWebp     ImageResourceAvailableVariants = "webp"
)

// Defines values for StorageUploadResponseAvailableVariants.
const (
	StorageUploadResponseAvailableVariantsAvif     StorageUploadResponseAvailableVariants = "avif"
	StorageUploadResponseAvailableVariantsOriginal StorageUploadResponseAvailableVariants = "original"
	StorageUploadResponseAvailableVariantsWebp     StorageUploadResponseAvailableVariants = "webp"
)

// Error defines model for Error.
type Error struct {
	// Details Additional error details
	Details *string `json:"details,omitempty"`

	// Error Error type identifier
	Error string `json:"error"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// FormatVariants defines model for FormatVariants.
type FormatVariants struct {
	Medium   *VariantSize `json:"medium,omitempty"`
	Original *VariantSize `json:"original,omitempty"`
	Small    *VariantSize `json:"small,omitempty"`
}

// ImageResource defines model for ImageResource.
type ImageResource struct {
	// AvailableVariants List of available variant-families for this image
	AvailableVariants *[]ImageResourceAvailableVariants `json:"available_variants,omitempty"`
	ImageUuid         string                            `json:"image_uuid"`

	// Url Direct URL to the original image file
	Url *string `json:"url,omitempty"`

	// Variants URLs of available variants grouped by family
	Variants *struct {
		Avif     *FormatVariants `json:"avif,omitempty"`
		Original *FormatVariants `json:"original,omitempty"`
		Webp     *FormatVariants `json:"webp,omitempty"`
	} `json:"variants,omitempty"`

	// ViewUrl Share page URL (HTML view)
	ViewUrl *string `json:"view_url,omitempty"`
}

// ImageResourceAvailableVariants defines model for ImageResource.AvailableVariants.
type ImageResourceAvailableVariants string

// Pong defines model for Pong.
type Pong struct {
	// Ping Simple response confirming API availability
	Ping string `json:"ping"`
}

// StorageUploadResponse defines model for StorageUploadResponse.
type StorageUploadResponse struct {
	// AvailableVariants List of available variant-families for this image
	AvailableVariants *[]StorageUploadResponseAvailableVariants `json:"available_variants,omitempty"`

	// Duplicate Indicates the uploaded file already exists for this user
	Duplicate *bool `json:"duplicate,omitempty"`

	// ImageUuid UUID of the uploaded image
	ImageUuid *string `json:"image_uuid,omitempty"`

	// Url Direct URL to the original image file
	Url *string `json:"url,omitempty"`

	// Variants URLs of available variants grouped by family
	Variants *struct {
		Avif     *FormatVariants `json:"avif,omitempty"`
		Original *FormatVariants `json:"original,omitempty"`
		Webp     *FormatVariants `json:"webp,omitempty"`
	} `json:"variants,omitempty"`

	// ViewUrl Share page URL (HTML view)
	ViewUrl *string `json:"view_url,omitempty"`
}

// StorageUploadResponseAvailableVariants defines model for StorageUploadResponse.AvailableVariants.
type StorageUploadResponseAvailableVariants string

// UploadSessionRequest defines model for UploadSessionRequest.
type UploadSessionRequest struct {
	// FileSize File size in bytes.
	FileSize int64 `json:"file_size"`
}

// UploadSessionResponse defines model for UploadSessionResponse.
type UploadSessionResponse struct {
	// ExpiresAt Expiration time as a Unix timestamp (seconds).
	ExpiresAt int64 `json:"expires_at"`

	// MaxBytes Maximum file size in bytes accepted with this token.
	MaxBytes int64 `json:"max_bytes"`

	// PoolId Identifier of the selected storage pool.
	PoolId int64 `json:"pool_id"`

	// Token Time-limited upload token (Bearer token).
	Token string `json:"token"`

	// UploadUrl Absolute URL of the upload endpoint.
	UploadUrl string `json:"upload_url"`
}

// UserAccount defines model for UserAccount.
type UserAccount struct {
	// ApiKeyLastUsedAt Last usage timestamp of the current API key
	ApiKeyLastUsedAt *time.Time `json:"api_key_last_used_at"`

	// CreatedAt Registration timestamp
	CreatedAt time.Time `json:"created_at"`

	// Email Linked email address
	Email openapi_types.Email `json:"email"`

	// Id User ID
	Id int64 `json:"id"`

	// LastLoginAt Timestamp of the last login (if available)
	LastLoginAt *time.Time        `json:"last_login_at"`
	Limits      UserAccountLimits `json:"limits"`

	// Plan Current subscription plan
	Plan        string                 `json:"plan"`
	Preferences UserAccountPreferences `json:"preferences"`
	Stats       UserAccountStats       `json:"stats"`

	// Status Account status
	Status string `json:"status"`

	// Username User display name
	Username string `json:"username"`
}

// UserAccountLimits defines model for UserAccountLimits.
type UserAccountLimits struct {
	// AllowedThumbnailFormats Available thumbnail formats
	AllowedThumbnailFormats []string `json:"allowed_thumbnail_formats"`

	// CanMultiUpload Whether multi-upload is allowed
	CanMultiUpload bool `json:"can_multi_upload"`

	// DirectUploadEnabled Global setting for direct uploads
	DirectUploadEnabled bool `json:"direct_upload_enabled"`

	// ImageUploadEnabled Global setting for image uploads
	ImageUploadEnabled bool `json:"image_upload_enabled"`

	// MaxUploadBytes Maximum upload size per file (in bytes)
	MaxUploadBytes int64 `json:"max_upload_bytes"`

	// StorageQuotaBytes Total available storage (null if unlimited)
	StorageQuotaBytes *int64 `json:"storage_quota_bytes"`
}

// UserAccountPreferences defines model for UserAccountPreferences.
type UserAccountPreferences struct {
	// ThumbnailAvif Prefers AVIF thumbnails
	ThumbnailAvif bool `json:"thumbnail_avif"`

	// ThumbnailOriginal Prefers original thumbnails
	ThumbnailOriginal bool `json:"thumbnail_original"`

	// ThumbnailWebp Prefers WebP thumbnails
	ThumbnailWebp bool `json:"thumbnail_webp"`
}

// UserAccountStats defines model for UserAccountStats.
type UserAccountStats struct {
	Albums struct {
		// Count Number of created albums
		Count int64 `json:"count"`
	} `json:"albums"`
	Images struct {
		// Count Number of stored images
		Count int64 `json:"count"`

		// StorageRemainingBytes Remaining storage in bytes (null if unlimited)
		StorageRemainingBytes *int64 `json:"storage_remaining_bytes"`

		// StorageUsedBytes Used storage in bytes
		StorageUsedBytes int64 `json:"storage_used_bytes"`
	} `json:"images"`
}

// VariantSize defines model for VariantSize.
type VariantSize struct {
	// Animated Whether this asset is animated (e.g., GIF/WebP)
	Animated *bool `json:"animated,omitempty"`

	// Bytes File size in bytes if known
	Bytes *int64 `json:"bytes,omitempty"`

	// Height Pixel height if known
	Height *int `json:"height,omitempty"`

	// MimeType MIME type of this asset
	MimeType *string `json:"mime_type,omitempty"`
	Url      string  `json:"url"`

	// Width Pixel width if known
	Width *int `json:"width,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = Error

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = Error

// PostDirectUploadMultipartBody defines parameters for PostDirectUpload.
type PostDirectUploadMultipartBody struct {
	File openapi_types.File `json:"file"`

	// Token Alternative to Authorization header: pass upload token as multipart field
	Token *string `json:"token,omitempty"`
}

// PostDirectUploadMultipartRequestBody defines body for PostDirectUpload for multipart/form-data ContentType.
type PostDirectUploadMultipartRequestBody PostDirectUploadMultipartBody

// PostUserUploadSessionJSONRequestBody defines body for PostUserUploadSession for application/json ContentType.
type PostUserUploadSessionJSONRequestBody = UploadSessionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get image resource
	// (GET /images/{uuid})
	GetImage(c *fiber.Ctx, uuid string) error
	// Get processing status
	// (GET /images/{uuid}/status)
	GetImageStatus(c *fiber.Ctx, uuid string) error
	// Health check endpoint
	// (GET /ping)
	GetPing(c *fiber.Ctx) error
	// Direct storage upload
	// (POST /upload)
	PostDirectUpload(c *fiber.Ctx) error
	// Issue direct upload session
	// (POST /upload/sessions)
	PostUserUploadSession(c *fiber.Ctx) error
	// Get authenticated user profile
	// (GET /user/profile)
	GetUserProfile(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetImage operation middleware
func (siw *ServerInterfaceWrapper) GetImage(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid string

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", c.Params("uuid"), &uuid, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter uuid: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.GetImage(c, uuid)
}

// GetImageStatus operation middleware
func (siw *ServerInterfaceWrapper) GetImageStatus(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid string

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", c.Params("uuid"), &uuid, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter uuid: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.GetImageStatus(c, uuid)
}

// GetPing operation middleware
func (siw *ServerInterfaceWrapper) GetPing(c *fiber.Ctx) error {

	return siw.Handler.GetPing(c)
}

// PostDirectUpload operation middleware
func (siw *ServerInterfaceWrapper) PostDirectUpload(c *fiber.Ctx) error {

	c.Context().SetUserValue(UploadTokenAuthScopes, []string{})

	return siw.Handler.PostDirectUpload(c)
}

// PostUserUploadSession operation middleware
func (siw *ServerInterfaceWrapper) PostUserUploadSession(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.PostUserUploadSession(c)
}

// GetUserProfile operation middleware
func (siw *ServerInterfaceWrapper) GetUserProfile(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.GetUserProfile(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/images/:uuid", wrapper.GetImage)

	router.Get(options.BaseURL+"/images/:uuid/status", wrapper.GetImageStatus)

	router.Get(options.BaseURL+"/ping", wrapper.GetPing)

	router.Post(options.BaseURL+"/upload", wrapper.PostDirectUpload)

	router.Post(options.BaseURL+"/upload/sessions", wrapper.PostUserUploadSession)

	router.Get(options.BaseURL+"/user/profile", wrapper.GetUserProfile)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa/2/bOLL/Vwi990MKKLbTdt/rBTjgstuma2yyNfJle0AROLQ0srmRSC1JOfEW/t8P",
	"Q1IyJdGx02uCu8P9llgkZzjzme/8GiWiKAUHrlV0/DWSoErBFZh/fqTpBfxRgdL4XyK4Bm7+pGWZs4Rq",
	"JvjwdyU4/qaSBRQU//pfCVl0HP3PcHP00H5Vww9SChmt1+s4SkElkpV4SHQcjfmS5iwl0hIkJV3lgqbR",
	"Oo5OhZyxNAX+/FycJImouCZcaELzXNxDSrQgJchMyILoBVOEJmbxOo7GXIPkNLfHvYCILDmiQC5BErAL",
	"4+hXoU9FxdPnZ+EClKhkAkZAmaG5jqOJ1dWVEGdUzuEl2DAggZRkLAei2J9A4CEBSBUpc8qJkOSPSmhK",
	"clYwrZDJS5BLlsA1p0vKcjrLX4BPR5NUHtF1HF0JcU75yt1CPT8fV0KQgvJVbV1GINecVnohJPsTXgA5",
	"50wpxueoGeZMHckD146QZUlVZSmkhvQcUkavVuULaMmjSgokSzTSxYVuLx7dGHkpRQlSM+sjU9CU5e7P",
	"litJU4Z/0twaKqlXxhE80KJE/EXvqaYzqoAkgnMwjoVklOWQRnFkuDiOlJaMz1E8ULPQpmQ4MzwTlqJA",
	"MwayRYY5zzG1nmNqDwpQKEApai24TePnqqD8UAJNEcTuRvVqn9QJJxWHhxISFKddJ5KkkjJ0p3UcISQZ",
	"fjz+EtV81QffNBvE7HdItIsGBdW/Ucmoi1m0kfTEU01GcwVxR1uo3qrYhRR3+CX705irkGzOOM2fuE0V",
	"NH/annXguuOCzqF2u334NX5luvQk0tbdGVOaiIw0a4lbe5jRguUMFMkQQBjcWGEVyjQU5ijgKK8vGyHE",
	"0T3MyiiO6JJlnoY2IHI/UCnpCv83Z06rihk301teybzP83smIdHk+uIM469eAKkZsCwaxx/FUWbQEB1H",
	"lWQhQC/3xUnHJVycqaDIFJlLUZWQktmKGPGtorinE5bt0nsHxU9AWX+n0ccTd4WgtmRwPw1q43JBJZAS",
	"5Y4aOfj56vyM4PJXO03aU37ImieCz/uoLpn9tcMFQx9D6hQVfWbGZIFR5WQyrnXFcqZXLZdUIo1dfBqS",
	"IQ4vtZB0DtclpjgXjva/pyGmlY2dAf8+5qn5ooytVeaydXpFc/T7KwIPTGmPxUqBF0RmQuRAed/gO5Z1",
	"PX6PMmiRqS/7X9/wH+8beidbw7oEpZjgXrnZlhuqdIp5fp+B06YEYJzMVhrUwFc+4/r/3mJOwTgr0ISO",
	"GiYwLZqD7PmCDbGb3QxvcwjwUDIJakp1IGPDbyaHJZoVQKgilFxz9mD+VZoWJTlQkAieqlfB23RvEEcF",
	"fZia2/fJndMHvLpXLNWSIjRJoMRM7Z7phTVrLe6A70m0FCKfhsx83CSitbEryG1OqKxDJbh3TzKGpT6R",
	"K1bAoanwIHXOxHJPDn4EKkHa/4wE+67FrA9j+mSmRF5pi+iWsyLA01Iwrgc7HUwHVB69+kIb+cU+XHxd",
	"BgGoQLpGRSAOlWx6B6tpTpWeVgrSIADPqNKkwhzbQ5y7qMnVuTYx9Q5W/j1TquEQN0RxxKvcVdFaVhAQ",
	"cCKB6i30L2DOlPZMwHCwjVS/ECooy0Pxld9h0YFfCU1TCapdbpWg4W/u30EiCp+gPTNALBjFFEgyfu8f",
	"/vb1XlA2esnFnPGgYK662sD1xKwnB8wLOq++WS+uJbIjKHggO2t6KGVOA2b4kwOMqmbNz6YN05a9hAJr",
	"rwBHpYQMJPAEnsLWxNuF5ZamT7rVpVnvNlahAt71At13/y400WwZTlgUFtoFbIFMylSZ0xUxS1rSYQ+Q",
	"Izx3J9ToLRoycYPbhk0nec/8auE0um+LfIePOWvw0vE0tj861YuqmHHK8qnFY0iUTarULCb1Yk8K/eT2",
	"xkuAd6a3CeXToso1m1pf2+fj8wL0AiQxqw6dR2eqbvUGk9nUZJvuyClwvEbg6I+5mJnWrNZYkGCSbHe6",
	"wKEey5SffrZNdB87GmOIO3hHWuDkYBKDEqRNEw7qFOGVr6EfXr99/e7daLSXq3OBfmo6sduYuBKa5l4u",
	"XWcHB+jHCMtIxV2EfxXKFbZ4u22ZXU8oYS4DWNqiq234iB8xjx32Nml7w7bRbU6rK4m2OO1mRU5+G59u",
	"jC2MkM1Zfn0RPq+psPY+s648wud9htnk8bM6mgsw26MWd8WzQ9KXdcjoOrZZVQR+bzKu9pV+rYqZTXOd",
	"yyXuAM9ujvZJDjo3tuRCVzBI/BYGEet1ud3h792TTFpi1OGMz7eZ9UW9oDHopuT4Tpa9YcZkuVv4uFZe",
	"xVGz4N/8/9+8HY3evN7LpQUVFOSjr7VQW0wZN2GwElKz3xvug5SzAsG2PcjZYaVSoE2Ic+vJAQzmg5h8",
	"HJ8O0QhfBc14izT7pTbq8Y6Le/5oyT0KqW8BbL4IwHWCqRCxX/3jAyUvK2Cq3YyoE9vG5x/sSMTk0bUk",
	"Hukx7eoW3bNUL7Zxaz4+xmy3GJR5GCMKkkoyvbrEhNWq4KRkv8DqpApRdzWaSQk647Q4YrhiATQ1bTqb",
	"lUZ/PzyZjA9/MXVdnUAZApvWxhUWpzW9mSmkT2vh1IXrvoW4lwfVVtgEVJOUG+AZGhuGFlqXdlDHeCbq",
	"ASBNDFjcPYzcT8WDKVMv7fwucso0B6jj4dBk1Zl4GCRJ1Bv7ff508QsZ/0omF58+Xny4vCSH5FOWsYTR",
	"3ByKrDdUbL6lFhThgMWNRryYjDoB1/9xnJ2Pr3qMiBK4HeEMhJwP3SY1xLUYNZnO/UsNksSwsDyK4mgJ",
	"UlmOjwajwcj0A0vgtGTRcfTG/BRHJdULg5ah9SzDr1XF0jX+ModgAa4ryVWtm+uLM0J52u9pkpzxu7rn",
	"C1YMg8hwYKv3cYoJKuixa+GWVNICNEgVHX/5ajGIzG0QaPrCvjlY/74Z4nbrn5u4/Szl9Wj03YbC7fFa",
	"6NGFUbxsVsTR29HRtlMbNoet4brZ9Hb3puYdh+8JjBh9H/DlBiWiqqKgcmWF7+DZcBlHms5RAZZ9Fd3g",
	"iW1oDDd176MIuW/CiVM/KaVIwE7zmSJ4kxw0GPzgoiWDewMov12xHTOXTd36r4ecbnplb+pR8kKmG9sH",
	"v/nd8x39mX6LPPCsxIisGYRZfI1248t7z/VkhHlKbzoNQZDVs7tHQUWJssO8UvD5ZqKnBVmCZNkqNNDr",
	"wWfCzFzv2XyDmU2GxF8lKIqswiyF5npBkgUkdy19/LCPPtrvxzoqaWngZ59O3YL2NGC/Ow1suh+lUAEl",
	"2CiPKaE3L3ORIF+hEppQbfRNTYc2GN8H5BrVtgByu+lv3xJp1GwHYbeTT5dXxDE1VHZsom4JtaNGTeUc",
	"TAAakCvM0+rbuUMUYYV5lKMhXxGaaZBuaIGseY15dD9/VFCBCdANWvFUb2bMlH3bR+YVlZRrQO6peey3",
	"GeNRuRl6zoEj7CAdkInIc3L78cMVCXrSW1JxzXJyW/uJv6KB3w7IOCO31jvYX2LfmICn9fSFcvteZkA+",
	"L4B3zzEXrM8xg8nbmGSgkwXJvNlnHQNISjUlS0ZDHN92ZW16YEp48V9wcjukJRsuj5zubu2YCrmimlmz",
	"JFJUOuDcJ0JpO6a9rrM99/TsR5GuOhZq+iwllXqIOdUhMv6YGzbTXT9hnzGOVhIagIfnRie5sTvNlsbl",
	"nLhIbacRNmE+JiVVqp3LUkUaVknGIN/9oMnwehN06e0otn5GPxZ+wRB6COcsqZ4JIuLaft+8kaNqxZOF",
	"FFxUKl99U/T51izq6M3uTd3XqGbfD/sQCzw+xM2v/7J7c/dJ53cJAV/7BVk3NL/fUlvVgcGZnx8YGh+8",
	"PUL8ZBpZaO2tHjZxOw0wZBPKNRSlkFSutoSGJhq0YgT1n5p4YcDUGiYiaUm5ykCG3cu1AtkaxT/qY77d",
	"eoLvE17YgsNPDrZbcK0nplQFKVFNwvLC5jraw1w3r/v/CQP/FlvDXXtQC7wbf1LyPEYdhO1oq50qkMNS",
	"ijrSPZ5KuzGle14cu7E+5iRMaZao2Jirnfw1hbzXLMKUToWs7CMYI5s4Rp4T396LhhCqFUji5EHck7E+",
	"pp+/Kv8+Pn1XpdVXTX13Hy8K6+Sb9T6nmzfftqjuPKSDJeSiLMzw3qxqNa6Oh8NcJDRfCKWP343ejVw+",
	"GK3j/lhHpJV9vh44qNOKa465ae7Te24eqnfUphPg6p0+I20HqAz027a3gLxEcTRnOdMLnIWiLyinc0AR",
	"eTuM8PsbTvJZVQR3nNguf39Lu72kAimXLbXdOa7SXt+s/xEAAP//B56Edrk1AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
