ALTER TABLE images
ADD COLUMN has_webp BOOLEAN DEFAULT FALSE,
ADD COLUMN has_avif BOOLEAN DEFAULT FALSE,
ADD COLUMN has_thumbnail_small BOOLEAN DEFAULT FALSE,
ADD COLUMN has_thumbnail_medium BOOLEAN DEFAULT FALSE;
