CREATE TABLE IF NOT EXISTS images (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL UNIQUE,
    user_id BIGINT UNSIGNED NOT NULL,
    filename VARCHAR(255) NOT NULL,
    title VARCHAR(255),
    description TEXT,
    file_path VARCHAR(255) NOT NULL,
    file_type VARCHAR(50),
    width INT,
    height INT,
    filesize BIGINT,
    content_type VARCHAR(100),
    share_link VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_bin UNIQUE,
    downloads INT DEFAULT 0,
    views INT DEFAULT 0,
    is_public BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    -- Metadata fields
    camera_model VARCHAR(100),
    taken_at DATETIME,
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    exposure_time VARCHAR(50),
    aperture VARCHAR(50),
    iso INT,
    focal_length VARCHAR(50),
    metadata JSON,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
